language: python
python: '2.7'
sudo: required
dist: trusty
services:
- docker
git:
  submodules: false
before_install:
- git submodule update --init --recursive
- git submodule foreach git pull origin master
- sudo apt-get update -qq
- sudo apt-get install -qq squashfs-tools uuid python-apt python-pycurl btrfs-tools
install:
- sudo pip install ansible==2.4.3
- sudo pip install docker-py
script:
- cp -R roles/* squashible/roles/
- cp squashible.yml squashible/
- cd squashible
- sudo ansible-playbook -i hosts_generator.py squashible.yml -e "live_os=centos_7"
  -e "rootfs_size=4G"
- ls -lah live_output
- sudo chown -R travis:travis live_output
- cd live_output
- cp * ../../
- cd ../../

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "Antony Messerli"
  - git config --local user.email "amesserl@rackspace.com"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  api_key:
    secure: FDQjg954U4sZLb6pNG8LK1enRPyBc7ANI04bo7FNAmTTDgtahE89dySN0vwV3EqcxAF63TsbuQXHIOlMX0RhujP8gdAZERqGP9blfq7kNETS+m+rC7B4UnG8uQteCVY0ZTJaYuqEKhhGWZCjrZJKfuweXa8biICtUOaCjdVzbXVucTNQuPpRwt2F+iLzAKorCz3ekqH9B7u7GxxDDp0PnDlfC2gMpTOdJpsok0D3QYjPYrvmDQVtG5fXaRiXpgLS8dI7p5Lb4sP3JGU/ldKPsSkG3ZD8otTwMNANhdMbsD+8Btc9MCrQiAZzdtDW29MxMgZOZ2JB2rE0KbEJ8+N31XEnm4v2LBDmp186dx+E3V644c7pXp7NFs1fSic+1OR3OzQQoSJFROxUbD/yilaNtrQEWmYPzbySysXllIMBRhqoAWZzDWb4wYd4IIoieacq1H6KlREXAXCaMVcPKMPaGsQDDujc6a9KYYidIJHg/iSAdYAbVeWslif4E7tqsNNkYS+kMr7y7rn7MB0vqwBAxMJeSxRoNiNx5fh+OCoso54QPrUmmVmpsSOFc2hMJdScX5T2s0h1GFisG9aPAUbFHI8HmD5gwff5HhmBStAy+S7/76ELyuCK+hk12gqZICNgpoNOWofQDXCLwLJkUqmcprS+RZXzcpphKSLPnJBaJZs=
  file:
  - vmlinuz
  - initrd.img
  - rootfs.img
  on:
    repo: rcbops/rpc-deploy-utility-image
  skip_cleanup: true
