---
#
# Dell OpenManage Tooling (RHEL) - http://linux.dell.com/repo/hardware/dsu/ 
#

- name: Create DSU install path
  file:
    path: /usr/libexec/dell_dup
    state: directory
  when: ansible_distribution == "CentOS"

- name: Copy Dell repo keys to directory
  get_url:
    url: "http://linux.dell.com/repo/pgp_pubkeys/{{ item }}.asc"
    dest: "/usr/libexec/dell_dup/{{ item }}.asc"
  with_items:
    - '0x756ba70b1019ced6'
    - '0x1285491434D8786F'
    - '0xca77951d23b66a9d'
  when: ansible_distribution == "CentOS"

- name: Install Dell System Update repo key
  rpm_key:
    key: "http://linux.dell.com/repo/pgp_pubkeys/{{ item }}.asc"
    state: present
  with_items:
    - '0x756ba70b1019ced6'
    - '0x1285491434D8786F'
    - '0xca77951d23b66a9d'
  when: ansible_distribution == "CentOS"

- name: Copy dell-system-update.repo
  copy:
   src: dell-system-update.repo
   dest: /etc/yum.repos.d/dell-system-update.repo
  when: ansible_distribution == "CentOS"

- name: Install Dell Openmanage packages
  package:
    name: "{{ item }}"
  with_items:
    - dell-system-update
    - srvadmin-base
    - srvadmin-idrac
  ignore_errors: true
  when: ansible_distribution == "CentOS"

- name: Start Dell dataeng service
  service:
    name: dataeng
    enabled: yes 
  ignore_errors: yes
  when: ansible_distribution == "CentOS"
